// AlphaGong 龚诗模板
// 编辑好之后，请将档案更名为 gong.format.js
// 和 pet.text.js 一样是当模板字符串处理的
// 因为纯粹是作龚诗所以无需考虑 CQ 码，总没见龚诗还黄豆的

module.exports = [
    "《${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}》\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。",
    "《${arrayRandom(gongText['双字词'])}，${arrayRandom(gongText['单字'])}》\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。",
    "《${arrayRandom(gongText['单字'])}》\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。",
    "《${arrayRandom(gongText['三字词'])}》\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。\n${arrayRandom(gongText['三字词'])}${arrayRandom(gongText['单字'])}${arrayRandom(gongText['单字'])}${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['三字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。\n${arrayRandom(gongText['三字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['三字词'])}${arrayRandom(gongText['双字词'])}，\n${arrayRandom(gongText['单字'])}${arrayRandom(gongText['三字词'])}${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['三字词'])}，\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['三字词'])}。\n${arrayRandom(gongText['三字词'])}${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。\n${arrayRandom(gongText['双字词'])}${arrayRandom(gongText['双字词'])}。"
];
